In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
census_pop = pd.read_csv("../data/raw/DECENNIALDHC2020.P1-Data.csv")
census_pop = census_pop.iloc[1:]
census_pop = census_pop[["GEO_ID", "P1_001N"]]
census_pop = census_pop.rename(columns={"GEO_ID": "zip_code", "P1_001N": "population"})
census_pop["zip_code"] = census_pop["zip_code"].str[-5:]
census_pop["population"] = census_pop["population"].astype(int)

In [3]:
census_pop.head()

  zip_code  population
1    00601       17242
2    00602       37548
3    00603       49804
4    00606        5009
5    00610       25731

In [4]:
census_inc = pd.read_csv("../data/raw/ACSST5Y2024.S1901-Data.csv", dtype=str)
census_inc = census_inc.iloc[1:].copy()

In [5]:
census_inc = census_inc[["GEO_ID", "S1901_C01_012E"]].copy()
census_inc = census_inc.rename(
    columns={"GEO_ID": "zip_code", "S1901_C01_012E": "median_income"}
)
census_inc["zip_code"] = census_inc["zip_code"].str[-5:]
census_inc["median_income"] = pd.to_numeric(census_inc["median_income"], errors="coerce")
census_inc = census_inc.dropna(subset=["median_income"]).reset_index(drop=True)
census_inc["median_income"] = census_inc["median_income"].astype(int)
census_inc.head()

  zip_code  median_income
0    00601          19454
1    00602          21420
2    00603          20933
3    00606          20992
4    00610          24496

In [6]:
census = census_pop.merge(census_inc, on="zip_code", how="inner")
census.head()

  zip_code  population  median_income
0    00601       17242          19454
1    00602       37548          21420
2    00603       49804          20933
3    00606        5009          20992
4    00610       25731          24496

In [7]:
census.to_csv("../data/census_cleaned.csv", index=False)